<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <IsPackable>true</IsPackable>
    <PackageId>Downcastly.Attributes</PackageId>
    <Title>Downcastly.Attributes</Title>
    <Description>Enums and attributes for Downcastly project</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>alechka</Authors>
    <PackageTags>downcast downcastly</PackageTags>
    <Version>1.0.0</Version>
    <PackageProjectUrl>https://github.com/alechka/Downcastly</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  
</Project>
